export const historicTypes = {
    'yes': 'intérêt historique',
    'aircraft': 'Aéronef',
    'aqueduct': 'Aqueduc',
    'archaeological_site': 'Site archéologique',
    'battlefield': 'Champ de bataille',
    'bomb_crater': 'Cratère de bombe',
    'building': 'Bâtiment',
    'cannon': 'Canon',
    'castle': 'Château',
    'castle_wall': 'Mur défensif',
    'charcoal_pile': 'Tas de charbon',
    'church': 'Etablissement religieux',
    'city_gate': 'Porte de ville',
    'citywalls': 'Muraille',
    'farm': 'Ferme',
    'fort': 'Fort militaire',
    'gallows': 'Potence',
    'highwater_mark': 'Repère de crue',
    'locomotive': 'Locomotive',
    'manor': 'Manoir',
    'memorial': 'Mémorial',
    'mine': 'Mine',
    'mine_shaft': 'Mine',
    'milestone': 'Borne routière',
    'monastery': 'Monastère',
    'monument': 'Monument',
    'optical_telegraph': 'Télégraphe optique par sémaphore',
    'pillory': 'Pilori',
    'railway_car': 'Wagon',
    'railway_station': 'Gare ferroviaire',
    'ruins': 'Ruines',
    'rune_store': 'Pierre runique',
    'ship': 'Bateau ou sous-marin',
    'stone': 'Pierre',
    'tank': 'Tank',
    'technical_monument': 'Monument technique',
    'tomb': 'Tombe',
    'tower': 'Tour',
    'vehicle': 'Véhicule',
    'wayside_cross': 'Croix ou calvaire',
    'wayside_shrine': 'Oratoire',
    'wreck': 'Epave'
  }
  
  export const manMadeTypes = {
    'adit': 'Entrée de mine souterraine',
    'antenna': 'Antenne',	
    'beacon': 'Balise',
    'beehive': 'Ruche', 		
    'breakwater': 'Brise-lames',
    'bridge': 'Pont',
    'bunker_silo': 'Silo ouvert',
    'cairn': 'Cairn',
    'cellar_entrance': 'Entrée de cave',
    'chimney': 'Cheminée',
    'clearcut': 'Coupe rase',
    'column': 'Colonne',
    'communications_tower': 'Tour de télécommunications',
    'courtyard': 'Cour',
    'crane': 'Grue',
    'cross': 'Croix',
    'cutline': 'Ligne de coupe',
    'dolphin': 'Structure d\'amarrage',
    'dovecote': 'Colombier ou Pigeonnier',
    'dyke': 'Digue',
    'embankment': 'Remblai',
    'flagpole': 'Mât de drapeau',
    'flare': 'Tour',
    'footwear_decontamination': 'Equipement de décontamination de chaussures',
    'gantry': 'Panneau',
    'gasometer': ' Gazomètre',
    'goods_conveyor': 'Convoyeur pour transporter des objets',
    'groyne': 'Épi',
    'guard_stone': 'Chasse-roue',
    'insect_hotel': 'Hôtel à insecte',
    'kiln': 'Four',
    'lighthouse': 'Phare',
    'manhole': 'Trou',
    'mast': 'Mât',
    'mineshaft': 'Puits de mine',
    'monitoring_station': 'Station de surveillance ou de mesure',
    'nesting_site': 'Support de nid',
    'obelisk': 'Obélisque',
    'observatory': 'Observatoire',
    'offshore_platform': 'Plate-forme offshore',
    'petroleum_well': 'Puits de pétrole',
    'pier': 'Jetée ou ponton',
    'pipeline': 'Pipeline',
    'planter': 'Parterre de fleur',
    'pumping_rig': 'Pompe à tête de cheval',
    'pumping_station': 'Station de pompage',
    'reservoir_covered': 'Citerne',
    'silo': 'Silo',
    'snow_fence': 'Clôture à neige',
    'spoil_heap': 'Terril',
    'storage_tank': 'Réservoir de stockage de liquides ou de gaz',
    'street_cabinet': 'Armoire de rue',
    'stupa': 'Stūpa',
    'surveillance': 'Caméra de vidéo-surveillance',
    'survey_point': 'Poteau de triangulation ou sommet géodésique',
    'tailings_pond': 'Etang de résidus',
    'telescope': 'Télescope',
    'torii': 'Torii',
    'tower': 'Tour',
    'utility_pole': 'Poteau',
    'video_wall': 'Ecran',
    'wastewater_plant': 'Station d\'épuration ou de retraitement des eaux usées',
    'water_tap': 'Robinet d\'eau',
    'water_tower': 'Château d\'eau',
    'water_well': 'Puits',
    'water_works': 'Station de pompage d\'eau potable',
    'watermill': 'Moulin à eau',
    'wildlife_crossing': ' Écoduc',
    'windmill': 'Moulin à vent',
    'windpump': 'Pompe',
    'works': 'Bâtiment industriel',
    'yes': 'Structure artificielle' 
  }
  
  export const amenityTypes = {
    'bar': 'Bar',
    'biergarten': 'Brasserie',
    'cafe': 'Café',
    'fast_food': 'Restaurant',
    'food_court': 'Zone de restauration',
    'ice_cream': 'Glacier',
    'pub': 'Pub',
    'restaurant': 'Restaurant',
    'college': 'Établissement d\'enseignement supérieur',
    'driving_school': 'Auto-école',
    'kindergarten': 'École maternelle',
    'language_school': 'École de langues',
    'library': 'Bibliothèque',
    'music_school': 'École de musique',
    'school': 'École primaire, collège ou lycée',
    'university': 'Université',
    'bicycle_parking': 'Parking à vélos',
    'bicycle_repair_station': 'Point de réparation pour vélos en self-service',
    'bicycle_rental': 'Location de vélos',
    'boat_rental': 'Location de bateaux',
    'boat_sharing': 'Partage de bateaux',
    'bus_station': 'Gare routière',
    'car_rental': 'Location de voitures',
    'car_sharing': 'Station d\'autopartage',
    'car_wash': 'Station de lavage automobile',
    'charging_station': 'Installation de recharge pour véhicules électriques',
    'ferry_terminal': 'Terminal de ferry',
    'fuel': 'Station-service',
    'grit_bin': 'Sable ou sel contre le verglas',
    'motorcycle_parking': 'Parking pour véhicules deux-roues motorisés',
    'parking': 'Parking',
    'parking_entrance': 'Entrée ou sortie de parking',
    'parking_space': 'Place de parking',
    'taxi': 'Station de taxis',
    'atm': 'Distributeur automatique de billets',
    'bank': 'Banque',
    'bureau_de_change': 'Bureau de change',
    'baby_hatch': 'Boîte à bébé',
    'clinic': 'Clinique',
    'dentist': 'Dentiste',
    'doctors': 'Cabinet médical',
    'hospital': 'Hôpital',
    'nursing_home': 'Centre d\'hébergement pour personnes handicapées ou âgées',
    'pharmacy': 'Pharmacie',
    'social_facility': 'Services sociaux',
    'veterinary': 'Vétérinaire',
    'arts_centre': 'Centre culturel',
    'brothel': 'Bordel',
    'casino': 'Casino',
    'cinema': 'Cinéma',
    'community_centre': 'Salle des fêtes',
    'conference_centre': 'Salle de conférence',
    'events_venue': 'Centre de congrès',
    'fountain': 'Fontaine',
    'gambling': 'Salle de jeux',
    'love_hotel': 'Hôtel de passe',
    'nightclub': 'Boîte de nuit',
    'planetarium': 'Planétarium',
    'public_bookcase': 'Microbibliothèque',
    'social_centre': 'Pôle associatif',
    'stripclub': 'Boîte de strip-tease',
    'studio': 'Studio d\'enregistrement',
    'swingerclub': 'Club échangiste',
    'theatre': 'Théâtre',
    'courthouse': 'Palais de justice',
    'embassy': 'Ambassade',
    'fire_station': 'Caserne de pompiers',
    'police': 'Poste de police ou gendarmerie',
    'post_box': 'Boîte aux lettres',
    'post_depot': 'Dépôt de poste',
    'post_office': 'Bureau de poste',
    'prison': 'Prison',
    'ranger_station': 'Services publics des Parcs Nationaux',
    'townhall': 'Mairie',
    'bbq': 'Barbecue',
    'bench': 'Banc public',
    'dog_toilet': 'Canisette',
    'drinking_water': 'Source d\'eau potable',
    'give_box': 'Boîte à don',
    'parcel_locker': 'Machine de retrait ou dépôt de colis',
    'shelter': 'Abri contre le mauvais temps',
    'shower': 'Bains publics',
    'telephone': 'Cabine téléphonique',
    'toilets': 'Toilettes publiques',
    'water_point': 'Point d\'eau',
    'watering_place': 'Point d\'eau pour animaux',
    'sanitary_dump_station': 'Station de vidange sanitaire',
    'recycling': 'Point de collecte pour le recyclage',
    'waste_basket': 'Poubelle publique',
    'waste_disposal': 'Poubelle',
    'waste_transfer_station': 'Station de transfert de déchets',
    'animal_boarding': 'Pension animale',
    'animal_breeding': 'Alimentation animale',
    'animal_shelter': 'Refuge',
    'baking_oven': 'Four à pain',
    'childcare': 'Crêche',
    'clock': 'Horloge publique',
    'crematorium': 'Crématorium',
    'dive_centre': 'Centre de plongée',
    'funeral_hall': 'Centre funéraire',
    'grave_yard': 'Cimetière',
    'hunting_stand': 'Affût de chasse',
    'internet_cafe': 'Cybercafé',
    'kitchen': 'Cuisine',
    'kneipp_water_cure': 'Bain de pied extérieur',
    'lounger': 'Transat',
    'marketplace': 'Place de marché',
    'monastery': 'Monastère',
    'photo_booth': 'Cabine photographique automatique',
    'place_of_mourning': 'Centre funéraire',
    'place_of_worship': 'Édifice religieux',
    'public_bath': 'Bain publique',
    'public_building': 'Bâtiment public',
    'refugee_site': 'Camp de réfugié',
    'vending_machine': 'Distributeur automatique'
  }
  
  export const militaryTypes = {
    'airfield': 'Terrain d\'aviation militaire',
    'ammunition': 'Zone de stockage de munitions militaires',
    'barracks': 'Baraquements',
    'bunker': 'Casemate',
    'checkpoint': 'Point de contrôle militaire',
    'danger_area': 'Zone dangereuse militaire',
    'launchpad': 'Zone de lancement',
    'naval_base': 'Base navale',
    'nuclear_explosion_site': 'Site d\'essais d\'armes nucléaires',
    'obstacle_course': 'Parcours du combattant',
    'office': 'Bureaux militaires',
    'range': 'Terrain d\'exercice militaire',
    'training_area': 'Camp d\'entraînement militaire',
    'trench': 'Tranchées militaires'
  }
  
  export const memorialTypes = {
    'plaque': 'Plaque commémorative',
    'war_memorial': 'Mémorial de guerre',
    'statue': 'Statue',
    'bust': 'Buste',
    'stele': 'Stèle',
    'stone': 'Pierre'
  }
  
  export const artworkTypes = {
    'architecture': 'Bâtiment remarquable',
    'mural': 'Oeuvre d\'art mural',
    'mural_painting': 'Peinture murale',
    'painting': 'Peinture',
    'sculpture': 'Sculpture',
    'statue': 'Statue',
    'bust': 'Buste',
    'stone': 'Rocher',
    'installation': 'Installation artistique',
    'graffiti': 'Graffiti',
    'tilework': 'Carrelage',
    'mosaic': 'Mosaïc',
    'azulejo': 'Azulejo',
    'land_art': 'Land art',
    'landart': 'Land art',
    'streetart': 'Streetart',
    'street_art': 'Streetart',
    'fountain': 'Fontaine',
    'column': 'Colonne',
    'stele': 'Stèle'
  }
  
  export const railwayTypes = {
    'abandoned': 'Ancienne voie ferrée'
  }

  export const archaeologicalSiteType = {
    'city': 'Ville',
    'fortification': 'Fortification',
    'hut_circle': 'Hut circle',
    'megalith': 'Mégalithe',
    'minilith': 'Alignement de pierres',
    'necropolis': 'Nécropole',
    'petroglyph': 'Pétroglyphe',
    'roman_circus': 'Cirque romain',
    'roman_villa': 'Villa romaine',
    'settlement': 'Établissement humain',
    'tumulus': 'Tumulus'
  }

  export const megalithType = {
    'dolmen': 'Dolmen',
    'passage_grave': 'Tombe à couloir (dolmen)',
    'long_barrow': 'Tumulus allongé',
    'tholos': 'Tholos',
    'menhir': 'Menhir',
    'alignment': 'Alignement mégalithique',
    'stone_circle': 'Cercle de pierre',
    'stone_ship': 'Bateau de pierre',
    'cist': 'Ciste',
    'ring_cairn': 'Cairn circulaire',
    'nuraghe': 'Nuraghe',
    'well': 'Nuragic holy well',
    'chamber': 'Chambre'
  }